---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret
  data_bags_path: test/integration/data_bags
  attributes:
    percona:
      encrypted_data_bag: percona

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[build-essential]
      - recipe[moodle]
    attributes:
